BASE_TASK_CONFIG_PATH: "configs/tasks/multinav_mp3d.yaml"
TRAINER_NAME: "ppo"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 0
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 1
VIDEO_OPTION: ['disk']
TENSORBOARD_DIR: "tb_dir/tmp_from_dell"
TENSORBOARD_DIR_EVAL: "eval/tmp_from_dell4"
VIDEO_DIR: "video_dir"
TEST_EPISODE_COUNT: 800
EVAL_CKPT_PATH_DIR: "eval/tmp_from_dell4"
NUM_PROCESSES: 16  # train: 16, test: 18 - TODO: Need to change before real exam
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR",'SEMANTIC_SENSOR']
CHECKPOINT_FOLDER: "ckpt/tmp_from_dell"
NUM_UPDATES: 300000
LOG_INTERVAL: 1
CHECKPOINT_INTERVAL: 500

DETECTOR_TYPE: "GroundingDINO"  # [GroundingDINO, FasterRCNN, GoalMasking]

# hyeon: for pretrained U-Net
N_OBJECT_CLASSES: 17
IMG_SEGM_MODEL_DIR: "/home/ailab/Final_MCFMO_DINO/model_checkpoints/img_segm_obj27_0/"

RL:
  SUCCESS_REWARD: 5.0
  SUBSUCCESS_REWARD: 3.0
  FALSE_FOUND_PENALTY: False
  FALSE_FOUND_PENALTY_VALUE: 2.5
  OBJECT_CATEGORY_EMBEDDING_SIZE: 32
  PREVIOUS_ACTION_EMBEDDING_SIZE: 32
  PREVIOUS_ACTION: True
  PPO:
    # PPO params
    clip_param: 0.2
    ppo_epoch: 2
    num_mini_batch: 4
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.2
    num_steps: 100  # original: 128
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: True
    use_linear_lr_decay: True
    reward_window_size: 50
    use_normalized_advantage: False
    hidden_size: 768
    
    # Auxiliary losses coefficients
    aux_loss_seen_coef: 0.15
    aux_loss_direction_coef: 0.15
    aux_loss_distance_coef: 0.15

  MAPS:
    egocentric_map_size: 13
    global_map_size: 275
    global_map_depth: 32
    global_map_semantic: 17
    global_map_goal: 8
    coordinate_min: -110.0
    coordinate_max:  110.0
    object_ind_offset: 2
